# Generated by Django 5.2.5 on 2025-08-30 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desayuno', models.CharField(blank=True, max_length=200)),
                ('mediodia', models.CharField(blank=True, max_length=200)),
                ('comida', models.CharField(blank=True, max_length=200)),
                ('tarde', models.CharField(blank=True, max_length=200)),
                ('cena', models.CharField(blank=True, max_length=200)),
                ('noche', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('zona', models.CharField(choices=[('IN', 'Interior'), ('EX', 'Exterior')], max_length=2)),
                ('provincia', models.CharField(max_length=100)),
                ('precio', models.CharField(choices=[('BA', 'Barato'), ('ME', 'Medio'), ('CA', 'Caro')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='weekend.day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-friday'],
                'unique_together': {('user', 'friday')},
            },
        ),
        migrations.AddField(
            model_name='day',
            name='weekend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='weekend.weekend'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('weekend', 'date')},
        ),
    ]
