# Generated by Django 5.2.5 on 2025-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='zona',
            field=models.CharField(blank=True, choices=[('IN', 'Interior'), ('EX', 'Exterior')], max_length=2, null=True),
        ),
    ]
