# Generated by Django 5.2.5 on 2025-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekend', '0002_alter_plan_nombre_alter_plan_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.CharField(blank=True, choices=[('BA', 'Barato'), ('ME', 'Medio'), ('CA', 'Caro')], max_length=2, null=True),
        ),
    ]
